// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuvOGSrhgF0xvGILJTWNmCJGwfeYyUHNU',
    appId: '1:264759707331:web:91c3f5f89ebd331da6c476',
    messagingSenderId: '264759707331',
    projectId: 'eatro-db253',
    authDomain: 'eatro-db253.firebaseapp.com',
    storageBucket: 'eatro-db253.firebasestorage.app',
    measurementId: 'G-4ZDNCK8WTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsoEzKQe5Ft2PBK7lWhGPDC6tkhFGwLC4',
    appId: '1:264759707331:android:227ae82f583b3981a6c476',
    messagingSenderId: '264759707331',
    projectId: 'eatro-db253',
    storageBucket: 'eatro-db253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9NPCBlVPDRMM0RvdOr0CypeLi_yeqRZs',
    appId: '1:264759707331:ios:9f71c75889e70f75a6c476',
    messagingSenderId: '264759707331',
    projectId: 'eatro-db253',
    storageBucket: 'eatro-db253.firebasestorage.app',
    iosBundleId: 'com.example.eatro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9NPCBlVPDRMM0RvdOr0CypeLi_yeqRZs',
    appId: '1:264759707331:ios:9f71c75889e70f75a6c476',
    messagingSenderId: '264759707331',
    projectId: 'eatro-db253',
    storageBucket: 'eatro-db253.firebasestorage.app',
    iosBundleId: 'com.example.eatro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuvOGSrhgF0xvGILJTWNmCJGwfeYyUHNU',
    appId: '1:264759707331:web:b26df2320e53d030a6c476',
    messagingSenderId: '264759707331',
    projectId: 'eatro-db253',
    authDomain: 'eatro-db253.firebaseapp.com',
    storageBucket: 'eatro-db253.firebasestorage.app',
    measurementId: 'G-JXD3J3VVRS',
  );

}